### ISSUE TITLE
Error: EACCES: permission denied, open 'privkey.pem'

### ISSUE THREAD

**Issue by viniscoelho** [mendhak/docker-http-https-echo#14] opened 2020-11-25 10:34 UTC
I was consuming this image in one of our tests and since the latest update it stopped working.
The test is quite simple: make a request to the app and check the returned response. But instead, the pod is in a CrashLoopBackOff state and shows the following logs:
```
internal/fs/utils.js:308
    throw err;
    ^
Error: EACCES: permission denied, open 'privkey.pem'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (/app/index.js:67:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: 'privkey.pem'
}
```

Our setup cannot allow images to run as root, therefore this wouldn't be a valid solution.

**Comment by mendhak** [comment] 2020-11-25 20:05
I'm not familiar with kubernetes, but is this problem reproducible in normal Docker?   
Is it just a matter of running the application as a non-root `USER` in the Dockerfile? 

Regarding updates - the latest update was to set the [Node version to 14](https://github.com/mendhak/docker-http-https-echo/commit/78c4abb3a5265219d2e152e4d000891c2f05abec#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557) I wouldn't think that would cause a problem like this though.

**Comment by mendhak** [comment] 2020-11-25 22:02
I made a guess, I think I was able to recreate the problem by setting a `--user node` in the docker run command, and I got the same privkey.pem EACCES error. 

Can you try this tag: `mendhak/http-https-echo:issue-14-non-root`. 

You'll need to run as node user, and change the internal port to a high number.  I ran it like so:

    docker run --user node -e HTTP_PORT=8080 -e HTTPS_PORT=8443 -p 8080:8080 -p 8443:8443 --rm mendhak/http-https-echo

Is that what's called a [security context for a pod](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)?  Then I think you'd do this:

    securityContext:
        runAsUser: 1000

I found another way to run the container too,

    docker run --user node --sysctl net.ipv4.ip_unprivileged_port_start=0 -p 8080:80 -p 8443:443 --rm mendhak/http-https-echo

But I don't know what its equivalent would be.

**Comment by viniscoelho** [comment] 2020-11-25 22:24
Hi @mendhak, thanks for the quick reply! I was already setting the security context in my pod description. This new docker image made the trick :) Thanks a lot!

**Comment by mendhak** [comment] 2020-11-26 20:19
OK it's merged now, and `:latest` tag has this change.  Please switch to it when you can, because the `:issue-14-non-root` will disappear later.

**Closed by mendhak** 2020-11-26 20:19 UTC

**Comment by viniscoelho** [comment] 2020-11-26 20:33
Could you create a versioned tag? That would be easier to track in case of a breaking change.

**Comment by mendhak** [comment] 2020-11-26 20:56
Yes good idea.  Done, I've set Docker hub to build by git tag as the image tag, and arbitrarily chosen this issue as a starting point.  

So you can now use `mendhak/http-https-echo:14`

**Comment by mendhak** [comment] 2020-12-15 23:07
In case you or anyone is still looking, the `:15` tag now runs as a non root user by default thanks to Sispheor's latest PR.

**Comment by fidransky** [comment] 2021-03-12 11:07
> 
> 
> In case you or anyone is still looking, the `:15` tag now runs as a non root user by default thanks to Sispheor's latest PR.

This was actually a super useful comment. While the latest tag (`:18`) wasn't working for me in Openshift, `:15` is. Thanks!

**Comment by romans8** [comment] 2023-05-06 04:10
docker run --user node -e HTTP_PORT=8080 -e HTTPS_PORT=8443 -p 8080:8080 -p 8443:8443 -v /etc/ssl/certs/fullchain.pem:/app/fullchain.pem -v /etc/ssl/private/privkey.pem:/app/privkey.pem --rm mendhak/http-https-echo:issue-14-non-root
internal/fs/utils.js:308
    throw err;
    ^

Error: EACCES: permission denied, open 'privkey.pem'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (/app/index.js:73:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: 'privkey.pem'
}

**Comment by romans8** [comment] 2023-05-06 04:11
docker run --user node -p 8080:8080 -p 8443:8443 -v /etc/ssl/certs/fullchain.pem:/app/fullchain.pem -v /etc/ssl/private/privkey.pem:/app/privkey.pem --rm -t mendhak/http-https-echo:26
node:internal/fs/utils:347
    throw err;
    ^

Error: EACCES: permission denied, open 'privkey.pem'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.<anonymous> (/app/index.js:124:22)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: 'privkey.pem'
}
